# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2


pipelines:
  branches:
    development:
      - parallel:
        - step:
            name: 'Build and sync with DEV S3'
            script:
              - echo "Dev Build started"
              - pipe: atlassian/aws-s3-deploy:0.4.4
                variables:
                  AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $DEV_AWS_DEFAULT_REGION
                  S3_BUCKET: $DEVELOPMENT_S3_BUCKET_NAME
                  LOCAL_PATH: '$(pwd)'
              - echo "Dev Build ended"
        - step:
            name: 'Clear S3 and sync with Bitbucket Repo'
            trigger: manual
            script:
              - echo "Dev Build started for clearing S3 started"
              - pipe: atlassian/aws-s3-deploy:0.4.4
                variables:
                  DELETE_FLAG: 'true'
                  AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $DEV_AWS_DEFAULT_REGION
                  S3_BUCKET: $DEVELOPMENT_S3_BUCKET_NAME
                  LOCAL_PATH: '$(pwd)'
              - echo "Clearing S3 and Dev Build ended"  