INSERT INTO dwh_hint.ddl_gaia_status VALUES
(-1, 'UPDATED',''),
(-2, 'TO_BE_CANCELLED',''),
(-3, 'CANCELLED',''),
(-4, 'DELETED',''),
(-5, 'EDITED',''),
(-6, 'EXPIRED',''),
(-7, 'UNKNOWN',''),
(0, 'INACTIVE',''),
(1, 'ACTIVE',''),
(2, 'PENDING',''),
(3, 'TO_BE_BILLED',''),
(4, 'PROCESSED',''),
(7, 'DELIVERED',''),
(10, 'CONFIRMED','Transaction confirmed but not approved'),
(12, 'APPROVED','Transaction approved'),
(15, 'PASTDUE','Payment is not yet done'),
(16, 'REJECTED',''),
(18, 'PARTIALLY_COMPLETED',''),
(20, 'COMPLETED',''),
(25, 'FORGIVEN',''),
(30, 'COLLECTION',''),
(99, 'FAILED','');
