INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (0, 'Active');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (1, 'Archived');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (2, 'Pending');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (3, 'Default');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (4, 'Temporary');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (5, 'Completed');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (6, 'Abandoned');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (7, 'Updated');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (8, 'Ready for Activation');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (9, 'Invalid');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (10, 'Valid');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (11, 'To Be Cancelled');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (12, 'Suppressed');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (13, 'Failed');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (14, 'Initial');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (15, 'Partially Completed');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (16, 'In Progress');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (17, 'Approved');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (18, 'Declined');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (19, 'Submitted');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (20, 'Boarded');
INSERT INTO dwh_hint.ddl_kronos_status (status_key, status_defintion) VALUES (21, 'Canceled');
