INSERT INTO dwh_hint.ddl_kronos_status VALUES 
 (0, 'Active', ''),
 (1, 'Archived', ''),
 (2, 'Pending', ''),
 (3, 'Default', ''),
 (4, 'Temporary', ''),
 (5, 'Completed', ''),
 (6, 'Abandoned', ''),
 (7, 'Updated', ''),
 (8, 'Ready for Activation', ''),
 (9, 'Invalid', ''),
 (10, 'Valid', ''),
 (11, 'To Be Cancelled', ''),
 (12, 'Suppressed', ''),
 (13, 'Failed', ''),
 (14, 'Initial', ''),
 (15, 'Partially Completed', ''),
 (16, 'In Progress', ''),
 (17, 'Approved', 'Payment has been approved'),
 (18, 'Declined', 'Payment was declined'),
 (19, 'Submitted', ''),
 (20, 'Boarded', ''),
 (21, 'Canceled', '');