CREATE TABLE IF NOT EXISTS dwh_hint${environment}.settlement
(
id bigint NOT NULL ENCODE az64,
name varchar(65535) ENCODE lzo,
authorisation_id bigint ENCODE az64,
gateway_transaction_id bigint ENCODE az64,
external_id varchar(255) ENCODE lzo,
transaction_id varchar(255) ENCODE lzo,
payment_gateway_id bigint ENCODE az64,
amount varchar(1024) ENCODE lzo,
tendered varchar(1024) ENCODE lzo,
type varchar(16) ENCODE lzo,
reason varchar(255) ENCODE lzo,
currency varchar(8) ENCODE lzo,
account varchar(255) ENCODE lzo,
batch_id varchar(255) ENCODE lzo,
settlement_status varchar(255) ENCODE lzo,
settlement_date timestamp without time zone ENCODE az64,
signature varchar(65535) ENCODE lzo,
token varchar(65535) ENCODE lzo,
entry_mode varchar(24) ENCODE lzo,
authd_date timestamp without time zone ENCODE az64,
last_four varchar(8) ENCODE lzo,
bin_type varchar(16) ENCODE lzo,
card_brand varchar(255) ENCODE lzo,
funding_txn_id varchar(255) ENCODE lzo,
funding_id varchar(255) ENCODE lzo,
interchange_unit_fee varchar(1024) ENCODE lzo,
interchange_percentage_fee varchar(1024) ENCODE lzo,
plan_code varchar(255) ENCODE lzo,
downgrade_reason_codes varchar(255) ENCODE lzo,
invoice_number varchar(255) ENCODE lzo,
source_transaction_id varchar(255) ENCODE lzo,
terminal_number varchar(255) ENCODE lzo,
ach_return_code varchar(255) ENCODE lzo,
parent_retref varchar(255) ENCODE lzo,
status smallint ENCODE az64,
created_at timestamp without time zone ENCODE az64,
updated_at timestamp without time zone ENCODE az64,
canceled_at timestamp without time zone ENCODE az64,
deleted_at timestamp without time zone ENCODE az64,
encrypted_ref_id varchar(65535) ENCODE lzo
) DISTKEY(id)
;
