CREATE TABLE IF NOT EXISTS ${schema}${environment}.settlement
(
id bigint NOT NULL,
name varchar(65535),
authorisation_id bigint,
gateway_transaction_id bigint,
external_id varchar(255),
transaction_id varchar(255),
payment_gateway_id bigint,
amount varchar(1024),
tendered varchar(1024),
type varchar(16),
reason varchar(255),
currency varchar(8),
account varchar(255),
batch_id varchar(255),
settlement_status varchar(255),
settlement_date timestamp without time zone,
signature varchar(65535),
token varchar(65535),
entry_mode varchar(24),
authd_date timestamp without time zone,
last_four varchar(8),
bin_type varchar(16),
card_brand varchar(255),
funding_txn_id varchar(255),
funding_id varchar(255),
interchange_unit_fee varchar(1024),
interchange_percentage_fee varchar(1024),
plan_code varchar(255),
downgrade_reason_codes varchar(255),
invoice_number varchar(255),
source_transaction_id varchar(255),
terminal_number varchar(255),
ach_return_code varchar(255),
parent_retref varchar(255),
status smallint,
created_at timestamp without time zone,
updated_at timestamp without time zone,
canceled_at timestamp without time zone,
deleted_at timestamp without time zone,
encrypted_ref_id varchar(65535)
) DISTKEY(id)
;
