DROP TABLE IF EXISTS dwh_hint${environment}.settlement;

CREATE TABLE IF NOT EXISTS dwh_hint${environment}.settlement
(
  id                          bigint NOT NULL ENCODE RAW,
  name                        varchar(65535) ENCODE RAW,
  authorisation_id            bigint ENCODE RAW,
  gateway_transaction_id      bigint ENCODE RAW,
  external_id                 varchar(255) ENCODE RAW,
  transaction_id              varchar(255) ENCODE RAW,
  payment_gateway_id          bigint ENCODE RAW,
  amount                      varchar(1024) ENCODE RAW,
  tendered                    varchar(1024) ENCODE RAW,
  type                        varchar(16) ENCODE RAW,
  reason                      varchar(255) ENCODE RAW,
  currency                    varchar(8) ENCODE RAW,
  account                     varchar(255) ENCODE RAW,
  batch_id                    varchar(255) ENCODE RAW,
  settlement_status           varchar(255) ENCODE RAW,
  settlement_date             timestamp without time zone ENCODE RAW,
  signature                   varchar(65535) ENCODE RAW,
  token                       varchar(65535) ENCODE RAW,
  entry_mode                  varchar(24) ENCODE RAW,
  authd_date                  timestamp without time zone ENCODE RAW,
  last_four                   varchar(8) ENCODE RAW,
  bin_type                    varchar(16) ENCODE RAW,
  card_brand                  varchar(255) ENCODE RAW,
  funding_txn_id              varchar(255) ENCODE RAW,
  funding_id                  varchar(255) ENCODE RAW,
  interchange_unit_fee        varchar(1024) ENCODE RAW,
  interchange_percentage_fee  varchar(1024) ENCODE RAW,
  plan_code                   varchar(255) ENCODE RAW,
  downgrade_reason_codes      varchar(255) ENCODE RAW,
  invoice_number              varchar(255) ENCODE RAW,
  source_transaction_id       varchar(255) ENCODE RAW,
  terminal_number             varchar(255) ENCODE RAW,
  ach_return_code             varchar(255) ENCODE RAW,
  parent_retref               varchar(255) ENCODE RAW,
  status                      smallint ENCODE RAW,
  created_at                  timestamp without time zone ENCODE RAW,
  updated_at                  timestamp without time zone ENCODE RAW,
  canceled_at                 timestamp without time zone ENCODE RAW,
  deleted_at                  timestamp without time zone ENCODE RAW,
  encrypted_ref_id            varchar(65535) ENCODE RAW
) DISTKEY(id);
