DROP TABLE IF EXISTS dwh_hint${environment}.subscription;

CREATE TABLE IF NOT EXISTS dwh_hint${environment}.subscription
(
id                      bigint NOT NULL ENCODE RAW,
plan_id                 bigint ENCODE RAW,
payment_plan_id         bigint ENCODE RAW,
fulfillment_plan_id     bigint ENCODE RAW,
product_id              bigint ENCODE RAW,
quantity                integer ENCODE RAW,
unit_name               varchar(255) ENCODE RAW,
remaining_payment       integer ENCODE RAW,
balance                 integer ENCODE RAW,
price                   integer ENCODE RAW,
discount_amts           integer ENCODE RAW,
discount_percentages    integer ENCODE RAW,
coupons                 integer ENCODE RAW,
credits                 integer ENCODE RAW,
payments                integer ENCODE RAW,
total_installment       integer ENCODE RAW,
tax                     integer ENCODE RAW,
tax_percentage          integer ENCODE RAW,
subtotal                integer ENCODE RAW,
total                   integer ENCODE RAW,
start_date              timestamp without time zone ENCODE RAW,
end_date                timestamp without time zone ENCODE RAW,
end_count               integer ENCODE RAW,
end_unit                varchar(64) ENCODE RAW,,
proration               boolean,
auto_renewal            boolean,
renewal_count           integer ENCODE RAW,
name                    varchar(65535) ENCODE RAW,
canceled_at             timestamp without time zone ENCODE RAW,
deleted_at              timestamp without time zone ENCODE RAW,
status                  smallint ENCODE RAW,
created_at              timestamp without time zone ENCODE RAW,
updated_at              timestamp without time zone ENCODE RAW,
encrypted_ref_id         varchar(65535) ENCODE RAW,
external_subscription_id varchar(65535) ENCODE RAW,
offering_id              varchar(65535)  ENCODE RAW
) DISTKEY(id);
