CREATE TABLE IF NOT EXISTS dwh_hint${environment}.subscription
(
id                      bigint NOT NULL ENCODE az64,
plan_id                 bigint ENCODE az64,
payment_plan_id         bigint ENCODE az64,
fulfillment_plan_id     bigint ENCODE az64,
product_id              bigint ENCODE az64,
quantity                integer ENCODE az64,
unit_name               varchar(255) ENCODE lzo,
remaining_payment       integer ENCODE az64,
balance                 integer ENCODE az64,
price                   integer ENCODE az64,
discount_amts           integer ENCODE az64,
discount_percentages    integer ENCODE az64,
coupons                 integer ENCODE az64,
credits                 integer ENCODE az64,
payments                integer ENCODE az64,
total_installment       integer ENCODE az64,
tax                     integer ENCODE az64,
tax_percentage          integer ENCODE az64,
subtotal                integer ENCODE az64,
total                   integer ENCODE az64,
start_date              timestamp without time zone ENCODE az64,
end_date                timestamp without time zone ENCODE az64,
end_count               integer ENCODE az64,
end_unit                varchar(64) ENCODE lzo,,
proration               boolean,
auto_renewal            boolean,
renewal_count           integer ENCODE az64,
name                    varchar(65535) ENCODE lzo,
canceled_at             timestamp without time zone ENCODE az64,
deleted_at              timestamp without time zone ENCODE az64,
status                  smallint ENCODE az64,
created_at              timestamp without time zone ENCODE az64,
updated_at              timestamp without time zone ENCODE az64,
encrypted_ref_id         varchar(65535) ENCODE lzo,
external_subscription_id varchar(65535) ENCODE lzo,
offering_id              varchar(65535)  ENCODE lzo
) DISTKEY(id)
;
