----- Data Pipeline: v4_g_settlement ---------------------
----- Redshift Table: v4_g_settlement ---------------------
----- Looker View: settlement ---------------------


SELECT id,
  name,
  authorisation_id,
  gateway_transaction_id,
  external_id,
  transaction_id,
  payment_gateway_id,
  amount*100,
  tendered*100,
  type,
  reason,
  currency,
  account,
  batch_id,
  settlement_status,
  settlement_date,
  signature,
  token,
  entry_mode,
  authd_date,
  last_four,
  bin_type,
  card_brand,
  funding_txn_id,
  funding_id,
  interchange_unit_fee,
  interchange_percentage_fee,
  plan_code,
  downgrade_reason_codes,
  invoice_number,
  source_transaction_id,
  terminal_number,
  ach_return_code,
  parent_retref,
  status,
  created_at,
  updated_at,
  canceled_at,
  deleted_at,
  encrypted_ref_id
FROM public.v4_g_settlement